apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: cilium-envoy
    app.kubernetes.io/name: cilium-envoy
    k8s-app: cilium-envoy
resources:
- rbac
- workload
